<template>
  <div
    class="panel-body text-center panel-body-group-not-done"
    style="position: relative; height: 100%"
  >
    <v-row class="row-group-not-done">
      <v-col cols="4" @click="headerAllClick()" style="padding: 0">
        <span id="655Header" :class="{ isSelected: category == '' }">
          Tất cả
        </span>
      </v-col>
      <v-col cols="4" @click="header655Click()" style="padding: 0">
        <span id="655Header" :class="{ isSelected: category == '23' }">
          POWER 6/55
        </span>
      </v-col>
      <v-col cols="4" @click="header645Click()" style="padding: 0">
        <span id="645Header" :class="{ isSelected: category == '21' }">
          MEGA 6/45
        </span>
      </v-col>
    </v-row>
    <div
      style="height: calc(100vh - 130px)"
      id="divListGroup"
      v-if="groupData.length > 0"
    >
      <div class="form-group" v-for="(group, index) in groupData" :key="index">
        <v-row
          class="homeDivTicker homeDivTickerGroupNotDone"
          @click="goGroupDoneDetail(group.id)"
        >
          <v-col cols="4" class="group-left" style="padding: 0">
            <div>
              <span class="nameBao"> {{ group.name.split("-")[1] }} </span>
            </div>
            <img
              width="80px"
              style="margin: 5px 0px"
              height="auto"
              src="/power655_logo.png"
              class="group-top-img"
              v-if="group.category == 23"
            />
            <img
              width="80px"
              style="margin: 5px 0px"
              height="auto"
              src="/mega645_logo.png"
              class="group-top-img"
              v-else
            />
            <p class="nameBao">Bạn đã góp</p>
            <p :class="group.percentageOfShares > 0 ? 'textGreen' : 'textRed'">
              {{ group.percentageOfShares }}%
            </p>
          </v-col>
          <v-col cols="8" class="text ml-4" style="padding: 0">
            <p style="">
              Nhóm: #{{ group.id }}
              <span class="finishText">
                Hoàn thành:
                <span class="textRed">{{ group.procress }}%</span>
              </span>
            </p>
            <p style="">Kỳ quay: #{{ group.drawInfo.drawId }}</p>
            <p style="">Số thành viên: {{ group.numberOfMembers }}</p>
            <p style="">
              Số tiền: {{ $formatMoney({ amount: group.moneyOfShares }) }}đ
            </p>
            <p style="">Thời gian đóng: {{ group.timeCutOff }}</p>
          </v-col>
        </v-row>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      category: "23",
      status: "-2",
      groupData: [],
    };
  },
  mounted() {
    this.getListGroup();
  },
  methods: {
    goGroupDoneDetail(id) {
      this.$router.push({
        path: '/momo/group_done/' + id,
        query: {}
      })
    },
    headerAllClick() {
      this.category = "";
      this.getListGroup();
    },
    header655Click() {
      this.category = "23";
      this.getListGroup();
    },
    header645Click() {
      this.category = "21";
      this.getListGroup();
    },

    getListGroup() {
      this.$store.dispatch("app/toggleOverlay", true);
      //   let data = {
      //     category: this.category,
      //     status: this.status,
      //   };
      //   let url = "https://luckybest.vn/momo_v2/action/common/getListGroup";
      let res = null;
      if (this.category == "23") {
        res = {
          result: 0,
          data: [
            {
              enableLeaveGroup: 0,
              numberOfMembers: 19,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 21,
              minAmountContribute: 5000,
              prizeWinAfterTax: 0,
              id: 20543,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 500000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 5 - 020543",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 18,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 18,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20581,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020581",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20592,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020592",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20612,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020612",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20632,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020632",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 18,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 18,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20567,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020567",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20582,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020582",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20583,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020583",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20652,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020652",
              category: 23,
              prizeWinAmount: 0,
            },
          ],
          requestId: 0,
          resultDesc: "SUCCESS",
        };
      } else if (this.category == "21") {
        res = {
          result: 0,
          data: [
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20271,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020271",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20273,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020273",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 8,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 9,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20275,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020275",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 2,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 5,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20293,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020293",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20295,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020295",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 24,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 25,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20296,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020296",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20374,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020374",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 16,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 16,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20415,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020415",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20489,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020489",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 16,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 16,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20565,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020565",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 13,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 14,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20292,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020292",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 9,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20315,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020315",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20385,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020385",
              category: 21,
              prizeWinAmount: 0,
            },
          ],
          requestId: 0,
          resultDesc: "SUCCESS",
        };
      } else {
        res = {
          result: 0,
          data: [
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20271,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020271",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20385,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020385",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 9,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20315,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020315",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 13,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 14,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20292,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020292",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 16,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 16,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20565,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020565",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20273,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020273",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 8,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 9,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20275,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020275",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 2,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 5,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20293,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020293",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20295,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020295",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 24,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 25,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20296,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020296",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20374,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020374",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 16,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 16,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20415,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020415",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 12,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 12,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20489,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 2,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020489",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 19,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 21,
              minAmountContribute: 5000,
              prizeWinAfterTax: 0,
              id: 20543,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 500000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 5 - 020543",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 18,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 18,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20581,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020581",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20592,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020592",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20612,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020612",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20632,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020632",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20672,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020672",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 18,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 18,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20567,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 280000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020567",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20582,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020582",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 10,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 10,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20583,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020583",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20652,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 2,
              timeCutOff: "18/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 100,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020652",
              category: 23,
              prizeWinAmount: 0,
            },
          ],
          requestId: 0,
          resultDesc: "SUCCESS",
        };
      }
      this.groupData = res.data;
      if (this.groupData.length > 0) {
        this.$store.dispatch("app/toggleOverlay", false);
      }
    },
  },
};
</script>