<template>
  <div
    class="panel-body text-center panel-body-group-not-done"
    style="position: relative; height: 100%"
  >
    <v-row class="row-group-not-done">
      <v-col cols="6" @click="header655Click()" style="padding: 0">
        <span id="655Header" :class="{ isSelected: category == '23' }">
          POWER 6/55
        </span>
      </v-col>
      <v-col cols="6" @click="header645Click()" style="padding: 0">
        <span id="645Header" :class="{ isSelected: category == '21' }">
          MEGA 6/45
        </span>
      </v-col>
    </v-row>
    <v-row class="row-group-not-done">
      <v-col cols="6" style="padding: 0">
        <v-select
          v-model="selectedSort"
          :items="$store.state.app.sortGroupNotDone"
          label="Sắp xếp"
          dense
          solo
        ></v-select>
      </v-col>
      <v-col cols="6" style="padding: 0">
        <button class="btn btn-go-group-done" @click="goGroupDone()">
          Nhóm đã hoàn thành
        </button>
      </v-col>
    </v-row>
    <div
      id="divSearchInput"
      class="form-group has-feedback has-search"
      style="background-color: black; border-radius: 4px"
      v-if="isSearch == true"
    >
      <input
        id="searchInput"
        type="text"
        class="form-control inputSearch"
        placeholder="Tìm kiếm..."
      />
    </div>
    <div style="height: calc(100vh - 130px)" id="divListGroup">
      <div class="form-group" v-for="(group, index) in groupData" :key="index">
        <v-row
          class="homeDivTicker homeDivTickerGroupNotDone"
          @click="goGroupNotDoneDetail(14792)"
        >
          <v-col cols="4" class="group-left" style="padding: 0">
            <div>
              <span class="nameBao"> {{ group.name.split("-")[1] }} </span>
            </div>
            <img
              width="80px"
              style="margin: 5px 0px"
              height="auto"
              src="/power655_logo.png"
              class="group-top-img"
              v-if="group.category == 23"
            />
            <img
              width="80px"
              style="margin: 5px 0px"
              height="auto"
              src="/mega645_logo.png"
              class="group-top-img"
              v-else
            />
            <p class="nameBao">Bạn đã góp</p>
            <p :class="group.percentageOfShares > 0 ? 'textGreen' : 'textRed'">
              {{ group.percentageOfShares }}%
            </p>
          </v-col>
          <v-col cols="8" class="text ml-4" style="padding: 0">
            <p style="">
              Nhóm: #{{ group.id }}
              <span class="finishText">
                Hoàn thành:
                <span class="textRed">{{ group.procress }}%</span>
              </span>
            </p>
            <p style="">Kỳ quay: #{{ group.drawInfo.drawId }}</p>
            <p style="">Số thành viên: {{ group.numberOfMembers }}</p>
            <p style="">
              Số tiền: {{ $formatMoney({ amount: group.moneyOfShares }) }}đ
            </p>
            <p style="">Thời gian đóng: {{ group.timeCutOff }}</p>
          </v-col>
        </v-row>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    isSearch: Boolean,
  },
  data() {
    return {
      category: "23",
      status: "",
      selectedSort: 3,
      groupData: [],
      valSort: {
        2: "timeCutOff",
        3: "procress",
        4: "percentageOfShares",
        5: "groupLevel",
      },
    };
  },
  watch: {
    selectedSort(sort) {
      if (sort != 1) {
        this.sortData();
      }
    },
  },
  mounted() {
    this.getListGroup();
  },
  methods: {
    goGroupDone() {
      alert("111");
    },
    goGroupNotDoneDetail(id) {
      alert(id);
    },
    header655Click() {
      this.category = "23";
      this.getListGroup();
    },
    header645Click() {
      this.category = "21";
      this.getListGroup();
    },

    getListGroup() {
      this.$store.dispatch("app/toggleOverlay", true);
      //   let data = {
      //     category: this.category,
      //     status: this.status,
      //   };
      //   let url = "https://luckybest.vn/momo_v2/action/common/getListGroup";\
      let res = null;
      if (this.category == "23") {
        res = {
          result: 0,
          data: [
            {
              enableLeaveGroup: 0,
              numberOfMembers: 4,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 5,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20481,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 56000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 80,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020481",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 150,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 165,
              minAmountContribute: 4620,
              prizeWinAfterTax: 0,
              id: 20254,
              groupLevel: 11,
              numberCoincy: 0,
              moneyOfShares: 3645180,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 11 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 89,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 1,
                  },
                ],
              },
              percentCashbacks: [1],
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 78.9,
              incomeTax: 0,
              name: "Power 6/55 - Bao 11 - 020254",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 23,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 23,
              minAmountContribute: 5000,
              prizeWinAfterTax: 0,
              id: 20373,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 215000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 43,
              incomeTax: 0,
              name: "Power 6/55 - Bao 5 - 020373",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 40,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 46,
              minAmountContribute: 2100,
              prizeWinAfterTax: 0,
              id: 20396,
              groupLevel: 10,
              numberCoincy: 0,
              moneyOfShares: 693000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 10 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 88,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 1,
                  },
                ],
              },
              percentCashbacks: [1],
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 33,
              incomeTax: 0,
              name: "Power 6/55 - Bao 10 - 020396",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 3,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 3,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20483,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 14000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 20,
              incomeTax: 0,
              name: "Power 6/55 - Bao 7 - 020483",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 11,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 11,
              minAmountContribute: 5000,
              prizeWinAfterTax: 0,
              id: 20414,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 85000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 17,
              incomeTax: 0,
              name: "Power 6/55 - Bao 5 - 020414",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 705,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 856,
              minAmountContribute: 9282,
              prizeWinAfterTax: 0,
              id: 14792,
              groupLevel: 18,
              numberCoincy: 0,
              moneyOfShares: 24504480,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 18 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 94,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 4,
                  },
                ],
              },
              percentCashbacks: [4],
              timeCutOff: "18/03/2021 00:00:00",
              prizeBonus: 0,
              procress: 13.2,
              incomeTax: 0,
              name: "Power 6/55 - Bao 18 - 014792",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 199,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 221,
              minAmountContribute: 5005,
              prizeWinAfterTax: 0,
              id: 16278,
              groupLevel: 15,
              numberCoincy: 0,
              moneyOfShares: 4584580,
              drawInfo: {
                drawId: "00554",
                openDate: "18/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 15 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 93,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 3,
                  },
                ],
              },
              percentCashbacks: [3],
              timeCutOff: "18/03/2021 00:00:00",
              prizeBonus: 0,
              procress: 9.16,
              incomeTax: 0,
              name: "Power 6/55 - Bao 15 - 016278",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 96,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 106,
              minAmountContribute: 1716,
              prizeWinAfterTax: 0,
              id: 17865,
              groupLevel: 13,
              numberCoincy: 0,
              moneyOfShares: 1134276,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 13 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 91,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 2,
                  },
                ],
              },
              percentCashbacks: [2],
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 6.61,
              incomeTax: 0,
              name: "Power 6/55 - Bao 13 - 017865",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 135,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 151,
              minAmountContribute: 3003,
              prizeWinAfterTax: 0,
              id: 17563,
              groupLevel: 14,
              numberCoincy: 0,
              moneyOfShares: 1984983,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 14 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 92,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 3,
                  },
                ],
              },
              percentCashbacks: [3],
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 6.61,
              incomeTax: 0,
              name: "Power 6/55 - Bao 14 - 017563",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 19,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 22,
              minAmountContribute: 4620,
              prizeWinAfterTax: 0,
              id: 20172,
              groupLevel: 12,
              numberCoincy: 0,
              moneyOfShares: 577500,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 12 Power",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 90,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 2,
                  },
                ],
              },
              percentCashbacks: [2],
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 6.25,
              incomeTax: 0,
              name: "Power 6/55 - Bao 12 - 020172",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 2,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 2,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20480,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 14000,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 5,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020480",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 1,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 1,
              minAmountContribute: 8400,
              prizeWinAfterTax: 0,
              id: 20474,
              groupLevel: 9,
              numberCoincy: 0,
              moneyOfShares: 8400,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 1,
              incomeTax: 0,
              name: "Power 6/55 - Bao 9 - 020474",
              category: 23,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 0,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 0,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20484,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 0,
              drawInfo: {
                drawId: "00553",
                openDate: "16/03/2021 18:00:00",
                category: 23,
              },
              groupStatus: 1,
              timeCutOff: "16/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 0,
              incomeTax: 0,
              name: "Power 6/55 - Bao 8 - 020484",
              category: 23,
              prizeWinAmount: 0,
            },
          ],
          requestId: 0,
          resultDesc: "SUCCESS",
        };
        this.groupData = res.data;
      } else {
        res = {
          result: 0,
          data: [
            {
              enableLeaveGroup: 0,
              numberOfMembers: 7,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 7,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20385,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 24500,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 35,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020385",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 8,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 8,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20296,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 70000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 25,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020296",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 4,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 4,
              minAmountContribute: 3500,
              prizeWinAfterTax: 0,
              id: 20415,
              groupLevel: 7,
              numberCoincy: 0,
              moneyOfShares: 14000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 20,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 7 - 020415",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 609,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 782,
              minAmountContribute: 9282,
              prizeWinAfterTax: 0,
              id: 6744,
              groupLevel: 18,
              numberCoincy: 0,
              moneyOfShares: 36255492,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 18 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 87,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 4,
                  },
                ],
              },
              percentCashbacks: [4],
              timeCutOff: "17/03/2021 00:00:00",
              prizeBonus: 0,
              procress: 19.53,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 18 - 006744",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 254,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 301,
              minAmountContribute: 5005,
              prizeWinAfterTax: 0,
              id: 10563,
              groupLevel: 15,
              numberCoincy: 0,
              moneyOfShares: 6231225,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 15 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 86,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 3,
                  },
                ],
              },
              percentCashbacks: [3],
              timeCutOff: "17/03/2021 00:00:00",
              prizeBonus: 0,
              procress: 12.45,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 15 - 010563",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 140,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 169,
              minAmountContribute: 3003,
              prizeWinAfterTax: 0,
              id: 12108,
              groupLevel: 14,
              numberCoincy: 0,
              moneyOfShares: 3282279,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 14 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 85,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 3,
                  },
                ],
              },
              percentCashbacks: [3],
              timeCutOff: "17/03/2021 00:00:00",
              prizeBonus: 0,
              procress: 10.93,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 14 - 012108",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 8,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 8,
              minAmountContribute: 4200,
              prizeWinAfterTax: 0,
              id: 20256,
              groupLevel: 9,
              numberCoincy: 0,
              moneyOfShares: 88200,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 10.5,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 9 - 020256",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 2,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 2,
              minAmountContribute: 7000,
              prizeWinAfterTax: 0,
              id: 20473,
              groupLevel: 8,
              numberCoincy: 0,
              moneyOfShares: 21000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 7.5,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 8 - 020473",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 13,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 13,
              minAmountContribute: 4620,
              prizeWinAfterTax: 0,
              id: 19821,
              groupLevel: 11,
              numberCoincy: 0,
              moneyOfShares: 304920,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 11 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 82,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 1,
                  },
                ],
              },
              percentCashbacks: [1],
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 6.6,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 11 - 019821",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 5,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 5,
              minAmountContribute: 4000,
              prizeWinAfterTax: 0,
              id: 20226,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 24000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 6,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 5 - 020226",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 9,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 9,
              minAmountContribute: 2100,
              prizeWinAfterTax: 0,
              id: 20277,
              groupLevel: 10,
              numberCoincy: 0,
              moneyOfShares: 94500,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 10 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 81,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 1,
                  },
                ],
              },
              percentCashbacks: [1],
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 4.5,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 10 - 020277",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 3,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 3,
              minAmountContribute: 4000,
              prizeWinAfterTax: 0,
              id: 20278,
              groupLevel: 5,
              numberCoincy: 0,
              moneyOfShares: 12000,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 3,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 5 - 020278",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 31,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 36,
              minAmountContribute: 1716,
              prizeWinAfterTax: 0,
              id: 18589,
              groupLevel: 13,
              numberCoincy: 0,
              moneyOfShares: 425568,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashback Bao 13 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 84,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 2,
                  },
                ],
              },
              percentCashbacks: [2],
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 2.48,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 13 - 018589",
              category: 21,
              prizeWinAmount: 0,
            },
            {
              enableLeaveGroup: 0,
              numberOfMembers: 14,
              pushRefundStatus: 0,
              refundStatus: 0,
              levelWin: 0,
              type: 1,
              percentageOfShares: 0,
              prize: 0,
              statusWin: 0,
              amountCashback: 0,
              numberOfTickets: 14,
              minAmountContribute: 4620,
              prizeWinAfterTax: 0,
              id: 18965,
              groupLevel: 12,
              numberCoincy: 0,
              moneyOfShares: 175560,
              drawInfo: {
                drawId: "00716",
                openDate: "17/03/2021 18:00:00",
                category: 21,
              },
              groupStatus: 1,
              cashBackInfo: {
                name: "Cashbach Bao 12 Mega",
                description: "Chương Trình Cashback Vé Bao Chung",
                startTime: "03/01/2021 17:00:00",
                id: 83,
                endTime: "30/12/2021 17:00:00",
                cashBackDetailInfos: [
                  {
                    recvCashbackName: "Tài khoản LuckyBest",
                    paymentVendor: 1,
                    recvCashBack: 1,
                    paymentVendorName: "Tài khoản LuckyBest",
                    percent: 2,
                  },
                ],
              },
              percentCashbacks: [2],
              timeCutOff: "17/03/2021 17:00:00",
              prizeBonus: 0,
              procress: 1.9,
              incomeTax: 0,
              name: "Mega 6/45 - Bao 12 - 018965",
              category: 21,
              prizeWinAmount: 0,
            },
          ],
          requestId: 0,
          resultDesc: "SUCCESS",
        };
        this.groupData = res.data;
      }
      this.sortData();
      if (this.groupData.length > 0) {
        this.$store.dispatch("app/toggleOverlay", false);
      }
    },

    sortData() {
      let sort = this.valSort[this.selectedSort];
      this.groupData.sort(this.$dynamicsort({ property: sort, order: "desc" }));
    },
  },
};
</script>